<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-07-31 16:16

$extensionClassesPath = t3lib_extMgm::extPath('marit_dam') . 'Classes/';

return array(
	'tx_maritdam_viewhelpers_abstractbackendviewhelper' => $extensionClassesPath . 'ViewHelpers/AbstractBackendViewHelper.php',
	'tx_extbase_persistence_storage_typo3dbbackend' => $extensionClassesPath . 'Xclass/ux_Tx_Extbase_Persistence_Storage_Typo3DbBackend.php',
);

?>