<?php

########################################################################
# Extension Manager/Repository config file for ext: "marit_dam"
#
# Auto generated by Extbase Kickstarter 2010-01-24
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'DAM Extbase Connector',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Marit AG Developer, Richard Schaufler, Markus Kleinhenz, Marco Huber, Lars Trebing',
	'author_email' => 'typo3-extension@marit.ag,richard.schaufler@marit.ag,markus.kleinhenz@marit.ag,marco.huber@marit.ag,lars.trebing@marit.ag',
	'author_company' => 'Marit AG,Marit AG,Marit AG,Marit AG,Marit AG',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,dam',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.5',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'dam'	=> ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>